# -*- coding: utf-8 -*-
"""Activity 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z6IuWJ-oUO6vCIVgISZLfQB8e7BWklLa
"""

import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline

# TODO: Modify this list to include the numerical columns
NUMERICAL_VARS = ['pclass', 'age', 'sibsp', 'parch', 'fare']

# Crear custom transformer
class MissingIndicator(BaseEstimator, TransformerMixin):

    def __init__(self, NUMERICAL_VARS):
        if not isinstance(NUMERICAL_VARS, list):
            self.NUMERICAL_VARS = [NUMERICAL_VARS]
        else:
            self.NUMERICAL_VARS = NUMERICAL_VARS

    def fit(self, X, y):
        return self

    def transform(self, X):
        # TODO: Put your code here
        numerical_data = X[self.NUMERICAL_VARS]
        null_data = numerical_data.isnull().astype(int)

        return null_data


# Leer el csv sin aplicar transformaciones
df = pd.read_csv("/content/raw-data.csv")

# Imprimir los primeros datos
print(df.head(10))

mi = MissingIndicator(NUMERICAL_VARS)
pipeline = Pipeline([('null_identifier', mi)])
null_data = pipeline.transform(df)
print(null_data.head(20))

joined_data = pd.concat([df, null_data], axis=1)
print(joined_data.head(20))

